### ISSUE TITLE
Fix compilation warnings

### ISSUE THREAD

**Issue by mpoquet** [netorcai/netorcai-client-fortran#5]
I just compiled 885d199 and it gave me the following warnings.
As unused variables are potential bugs, I report it here.
```
ninja -C build
ninja: Entering directory `build'
[17/72] Compiling Fortran object 'netorcai_fortran@sha/src_json.f90.o'.
../src/json.f90:1155:42:

     recursive function JsonNull_clone(this) result(res)
                                          1
Warning: Unused dummy argument ‘this’ at (1) [-Wunused-dummy-argument]
../src/json.f90:1148:45:

     recursive function JsonNull_toString(this) result(res)
                                             1
Warning: Unused dummy argument ‘this’ at (1) [-Wunused-dummy-argument]
../src/json.f90:1131:47:

     recursive subroutine JsonValue_destroy(this)
                                               1
Warning: Unused dummy argument ‘this’ at (1) [-Wunused-dummy-argument]
[72/72] Linking target json.
```

**Comment by zephyr111** [comment]
This is not a bug and this cannot be solved (except by disabling the warnings which is probably a bad idea).
Indeed, "this" is required for JsonNull_clone and JsonNull_toString since the two functions/subroutines override the ones inherited from JsonValue. But JsonNull does not use it as it is not needed to clone null or print "null". 
JsonValue_destroy is an empty base implementation for child class that does not need to allocate memory. As a result, this is not used, but needed for child classes.
So, to be clear, I think this is rather a bug of gfortran which is not able to see that "this" is required in member functions/subrountines...
Feel free to reopen the issue if you find any way to solve that...

**Comment by mpoquet** [comment]
Wow, FORTRAN programming seems great in 2019!

Isn't it possible to do a useless variable use so gfortran thinks this is used? Like C's `(void) var;`.

As last resort `-Wno-unused-parameter` could be set if gfortran does not detect unused parameters correctly.

**Comment by zephyr111** [comment]
> Wow, FORTRAN programming seems great in 2019!

Yes!
Note that this behavior of gfortran is similar to what can be seen in the Oracle Java™ compiler. 

> Isn't it possible to do a useless variable use so gfortran thinks this is used? Like C's `(void) var;`.

AFAIK, no.
See https://stackoverflow.com/questions/37500015/a-portable-way-to-suppress-an-unused-dummy-argument-warning-in-fortran.
But why to obfuscate a correct code just to avoid some useless warning?

> As last resort `-Wno-unused-parameter` could be set if gfortran does not detect unused parameters correctly.

Yes, its rather `-Wno-unused-dummy-argument`.
But as you said, it can also be useful to track bugs...
